/*
    tipo enumerazione che descrive i tipi di eventi da loggare al server
*/

public enum TipiDiLog {
    AVVIO_APPLICAZIONE,
    CLICK_PULSANTE_FILTRA_STATISTICHE,
    CLICK_PULSANTE_FILTRA_DETTAGLI,    
    CLICK_TABELLA_DETTAGLIO_SPESE,
    CLICK_PULSANTE_AGGIUNGI_SPESA,
    CLICK_PULSANTE_RIMUOVI_SPESA,
    CLICK_PULSANTE_SVUOTA_NUOVA_SPESA,
    TERMINE_APPLICAZIONE
}
